### ISSUE TITLE
add: Dijkstra's Algorithm

### ISSUE THREAD

**Issue by prateekpr17** [himanshu-03/Python-Data-Structures#69] opened 2023-10-14 13:49 UTC
### Describe the algorithm/code

Issue Description : Dijkstra's Algorithm is a widely used graph algorithm designed to find the shortest path from a source node to all other nodes in a weighted graph. It was developed by Dutch computer scientist Edsger W. Dijkstra in 1956. The algorithm is particularly effective when all edge weights are non-negative.

Hi there 👋

I'm excited to contribute to Hacktoberfest 2023, and I'd like to work on this issue. It looks like a great opportunity to learn and contribute to the project.

Please assign this issue to me, and I'll start working on it right away. If you have any specific instructions or guidelines, please let me know, and I'll make sure to follow them.

Thanks a lot for considering my request!

Best regards,
Prateek Sethi

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by statst** [comment] 2023-10-14 16:57
Hi Himanshu,
Colud you please assign this to me. I will add it. 
Thanks!

**Comment by prateekpr17** [comment] 2023-10-14 18:29
@statst I have already asked to be assigned to the issue. 
Please look for another issue

**Comment by himanshu-03** [comment] 2023-10-15 08:41
Hi @prateekpr17 !
You can start working on this issue! Do let me know if you need any help.

**Comment by himanshu-03** [comment] 2023-10-15 08:42
> Hi Himanshu, Colud you please assign this to me. I will add it. Thanks!

Hi @statst !
The issue is opened by @prateekpr17 and is assigned to him. Please look for any algorithms that u are acquainted with which are not currently present in any issues or repo.

**Comment by HarshallSonawane** [comment] 2023-10-15 12:52
Hello @prateekpr17 ,
Can you please assign me this issue

**Closed** 2023-10-25 16:03 UTC
Labels: hacktoberfest
